Remove retina endpoints
DIAGNijmegen/rse-gcapi pull request #154
Opened 2024-01-23 15:49 UTC by jmsmkn

See https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/236

2024-01-23 16:14 UTC, jmsmkn commented
The tests on main are likely broken.

2024-01-24 10:32 UTC, HarmvZ requested changes

2024-01-24 10:32 UTC, HarmvZ commented on tests/async_integration_tests.py
> +    ):
```suggestion
    async with AsyncClient(
        token=ARCHIVE_TOKEN, base_url=local_grand_challenge, verify=False
    ) as c_archive:
```

2024-03-05 11:44 UTC, HarmvZ commented
@jmsmkn I just came across this. Do you know what is going on with the failing tests?

2024-03-05 11:50 UTC, jmsmkn commented
Likely something with the GC fixtures changed and the tests broke. They should be re-run on main. If so, it is not ideal to rely on those fixtures kept on GC. Maybe we should create the fixtures that are needed for the GCAPI tests within this repo.

2024-03-05 12:02 UTC, HarmvZ approved these changes
Right, I just ran the tests on main and they are also broken. Issue here: https://github.com/DIAGNijmegen/rse-gcapi/issues/155. Let's merge this changeset since the failing tests are unrelated.

2024-03-05 14:07 UTC, jmsmkn commented
I'm not sure if this PR works, I think it's better to fix the tests on main first then merge/rebase.

2024-07-26 15:15 UTC, HarmvZ commented
Sidenote: Some references to retina stuff are still in the models.py file. This will automatically be removed when we regenerate the file.

2024-08-02 17:22 UTC, merged